import React from "react";
import { apple, bill, discount, google, map, videosora } from "../assets";
import styles, { layout } from "../style";
import { Link } from "react-router-dom";  // ← import Link

const Billing = () => {
  return (
    <section id="product" className={layout.sectionReverse}>
      <div className={layout.sectionImgReverse} style={{ position: "relative" }}>
        <video
          src={videosora}
          autoPlay
          loop
          muted
          className="w-full h-full relative z-5 object-cover rounded-lg"
        />
      </div>

      <div className={layout.sectionInfo}>
        <h2 className={styles.heading2}>
          Detect AI-Generated Videos <br className="sm:block hidden" /> with
          Advanced Trace Analysis
        </h2>
        <p className={`${styles.paragraph} max-w-[470px] mt-5`}>
          Our cutting-edge AI detection system identifies videos generated by
          models like Stable Diffusion, Pika, and Sora. Using trace analysis, we
          distinguish real footage from synthetic content.
        </p>

        {/* Link wraps the banner and navigates to your AI‑Detect route */}
        <Link to="/ai-detect" className="block">
          <div className="flex flex-row justify-center items-center py-4 px-6 bg-blue-gradient font-poppins font-medium text-[18px] text-primary rounded-[10px] mt-4 mb-2 hover:opacity-80 transition-opacity">
            <p className="text-black text-center">
              <span className="font-bold">Try it now:</span>{" "}
              <span className="text-lg">AI Detection Module</span>
            </p>
          </div>
        </Link>
      </div>
    </section>
  );
};

export default Billing;
